// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5aMkk1DL_AVbyPGzMaq1dwoZQQBagGzg',
    appId: '1:1095744431058:android:444a290a3c485871d41e0b',
    messagingSenderId: '1095744431058',
    projectId: 'forex-52a62',
    databaseURL: 'https://forex-52a62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'forex-52a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSyGvcxTyug6Uyu_70jag3P55jiFHjFk',
    appId: '1:1095744431058:ios:24c52daca8329d88d41e0b',
    messagingSenderId: '1095744431058',
    projectId: 'forex-52a62',
    databaseURL: 'https://forex-52a62-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'forex-52a62.appspot.com',
    iosBundleId: 'com.example.cepdovizapp',
  );

}